#!/bin/sh
# SPDX-License-Identifier: ISC
# Copyright (C) 2026 The leonhardweiler/dotfiles Authors

INPUT=$(cat /tmp/bash-last-input 2>/dev/null)

OUTPUT=$(tail -n 200 /tmp/terminal-output \
  | sed '
    s/\x1b\[[0-9;]*[a-zA-Z]//g
  ')

{
echo "INPUT:"
echo "$INPUT"
echo
echo "OUTPUT:"
echo "$OUTPUT"
} | wl-copy
