--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("WLR_DRM_DEVICES", "/dev/dri/by-path/pci-0000:34:00.0-card")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_SCALE_FACTOR", "1.6")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "0")
hl.env("GDK_SCALE", "2")
hl.env("XCURSOR_SIZE", "18")
hl.env("HYPRCURSOR_SIZE", "18")

--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
hl.monitor({
	output = "HDMI-A-1",
	mode = "preferred",
	position = "2560x0",
	scale = "1",
})

hl.monitor({
	output = "eDP-1",
	mode = "2560x1600@60",
	position = "auto",
	scale = "1.6",
})

-- monitor=eDP-1,2560x1600@60,auto,1.6
-- monitor=DP-1,preferred,auto,1.6,mirror,eDP-1

-- monitor= , preferred, auto, auto

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
local terminal = "alacritty"
local menu = "rofi -show drun"
local browser = "zen-browser"
local lock = "hyprlock"
local pass = "~/.config/scripts/rofi_keepassxc -d ~/.config/keepassxc/Passwords.kdbx"
local files = "rofi -show filebrowser"
local wsmgr = "~/.config/scripts/rofi_workspace_manager"

--################
--## AUTOSTART ###
--################

-- exec-once = $terminal
-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & firefox

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
	leaf = "global",
	enabled = true,
	speed = 10,
	bezier = "default",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 5.39,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 4.79,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "windowsIn",
	enabled = true,
	speed = 4.1,
	bezier = "easeOutQuint",
	style = "popin 87%",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 1.49,
	bezier = "linear",
	style = "popin 87%",
})
hl.animation({
	leaf = "fadeIn",
	enabled = true,
	speed = 1.73,
	bezier = "almostLinear",
})
hl.animation({
	leaf = "fadeOut",
	enabled = true,
	speed = 1.46,
	bezier = "almostLinear",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 3.03,
	bezier = "quick",
})
hl.animation({
	leaf = "layers",
	enabled = true,
	speed = 3.81,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "layersIn",
	enabled = true,
	speed = 4,
	bezier = "easeOutQuint",
	style = "fade",
})
hl.animation({
	leaf = "layersOut",
	enabled = true,
	speed = 1.5,
	bezier = "linear",
	style = "fade",
})
hl.animation({
	leaf = "fadeLayersIn",
	enabled = true,
	speed = 1.79,
	bezier = "almostLinear",
})
hl.animation({
	leaf = "fadeLayersOut",
	enabled = true,
	speed = 1.39,
	bezier = "almostLinear",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 3.5,
	bezier = "easeOutQuint",
	style = "slide",
})
hl.animation({
	leaf = "workspacesIn",
	enabled = true,
	speed = 3,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "workspacesOut",
	enabled = true,
	speed = 3.5,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "zoomFactor",
	enabled = true,
	speed = 7,
	bezier = "quick",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

local mainMod = "ALT" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + SHIFT + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exit())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + SHIFT + o", hl.dsp.exec_cmd(pass))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd(files))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd(browser))
hl.bind("SUPER + L", hl.dsp.exec_cmd(lock))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(wsmgr))

hl.bind(mainMod .. " + J", hl.dsp.layout("cyclenext"))
hl.bind(mainMod .. " + K", hl.dsp.layout("cycleprev"))

hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })

hl.bind(mainMod .. " + CTRL + SHIFT + h", hl.dsp.window.move({ x = -20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + SHIFT + j", hl.dsp.window.move({ x = 0, y = -20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + SHIFT + k", hl.dsp.window.move({ x = 0, y = 20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + SHIFT + l", hl.dsp.window.move({ x = 20, y = 0, relative = true }), { repeating = true })

hl.bind(mainMod .. " + m", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + z", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

hl.bind(mainMod .. " + Return", hl.dsp.layout("swapwithmaster"))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainMod .. " + F3", hl.dsp.exec_cmd("~/.config/scripts/vol_ctl up"), { locked = true, repeating = true })
hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd("~/.config/scripts/vol_ctl down"), { locked = true, repeating = true })
hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("~/.config/scripts/vol_ctl mute"), { locked = true, repeating = true })
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd("~/.config/scripts/bright_ctl up"), { locked = true, repeating = true })
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("~/.config/scripts/bright_ctl down"), { locked = true, repeating = true })
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))
hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 10,
		border_size = 2,
		-- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
		col = {
			active_border = "rgb(dddddd)",
			inactive_border = "rgb(595959)",
		},
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = true,
		-- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "master",
	},
	xwayland = {
		force_zero_scaling = true,
	},
	-- https://wiki.hypr.land/Configuring/Variables/#decoration
	decoration = {
		rounding = 0,
		rounding_power = 0,
	},
	-- https://wiki.hypr.land/Configuring/Variables/#animations
	animations = {
		enabled = false,
		-- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
		--        NAME,           X0,   Y0,   X1,   Y1
		-- Default animations, see https://wiki.hypr.land/Configuring/Animations/
		--           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
	},
	-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
	master = {
		new_status = "slave",
	},
	-- https://wiki.hypr.land/Configuring/Variables/#misc
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	--############
	--## INPUT ###
	--############
	-- https://wiki.hypr.land/Configuring/Variables/#input
	input = {
		kb_layout = "us",
		kb_variant = "colemak_dh",
		kb_options = "caps:swapescape",
		-- kb_layout = de
		repeat_delay = 300,
		follow_mouse = 1,
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = false,
		},
	},
	-- Example per-device config
	-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
	--##################
	--## KEYBINDINGS ###
	--##################
	-- See https://wiki.hypr.land/Configuring/Keywords/
	-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
	-- Move focus with mainMod + arrow keys
	-- resizeactive
	-- moveactive
	-- fullscreen
	-- Fenster zum Masterbereich verschieben
	-- Switch workspaces with mainMod + [0-9]
	-- Move active window to a workspace with mainMod + SHIFT + [0-9]
	-- Move/resize windows with mainMod + LMB/RMB and dragging
	-- Laptop multimedia keys for volume and LCD brightness
})

hl.on("hyprland.start", function()
	hl.exec_cmd("mako")
	hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
	hl.exec_cmd("~/files/projects/wallpaper/change-wallpaper.sh")
end)
