#!/bin/sh
# SPDX-License-Identifier: ISC
# Copyright (C) 2026 The leonhardweiler/dotfiles Authors
#
# dwl autostart - run via `dwl -s dwl-autostart` from dwl-run. dwl kills this
# process group on exit, so the backgrounded jobs stop with the session.

mako &                                                    
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
"$HOME/.local/bin/change-wallpaper"
"$HOME/.local/bin/dotfiles_sync"
while true; do "$HOME/.local/bin/bat_check"; sleep 120; done &
