#!/bin/bash

STEP=5

case "$1" in
  up)
    brightnessctl set +${STEP}%
    ;;
  down)
    brightnessctl set ${STEP}%-
    ;;
  *)
    echo "Usage: $0 {up|down}"
    exit 1
    ;;
esac

CURRENT=$(brightnessctl get)
MAX=$(brightnessctl max)
PERCENT=$((CURRENT * 100 / MAX))

notify-send \
  -h string:x-canonical-private-synchronous:brightness \
  -h int:value:$PERCENT \
  "Brightness" "${PERCENT}%"

